### ISSUE TITLE
arm64 image does not work

### ISSUE THREAD

**Issue by githubcdr** [thespad/docker-arr-in-one#15]
Hi,

I'm testing the arm64 build, but it seems this has some amd64 binaries that cause issues;

-  fatal: unable to exec /app/sonarr/bin/Sonarr: Exec format error

I made sure it pulled the arm64 image.

Regards

**Comment by thespad** [comment]
Thanks, it was a copy/paste error. I've pushed a fix and it should build correctly tonight.

**Comment by githubcdr** [comment]
Confirmed working, thanks!
